name: Repository Dispatch

on:
  repository_dispatch:
    types: [DEV Deploy Service]
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "release version (x.x.x)"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      if: ${{ github.event_name  == 'repository_dispatch' }}
      IMAGE_TAG: ${{ github.event.client_payload.version_tag }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      IMAGE_TAG: ${{ github.event.inputs.version }}

    steps:
      - uses: actions/checkout@v2

      - name: Check variable
        run: |
          echo ${IMAGE_TAG}
          printenv
          cat sample.config.yml
