name: Repository Dispatch
on:
  repository_dispatch:
    types: [call-deploy]

env:
  IMAGE_TAG: ${{ github.event.client_payload.version_tag }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check variable
        run: |
          cat sample.config.yml | grep image
          echo "IMAGE_TAG=$IMAGE_TAG"
