name: Repository Dispatch
on:
  repository_dispatch:
    types: [call-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: echo ${{ github.event.client_payload.sha }}

      - run: echo ${{ github.event.client_payload.my-key }}

