name: Repository Dispatch

on:
  repository_dispatch:
    types: [DEV Deploy Service]
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "release version (x.x.x)"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MANUAL_VALUE: ${{ github.event.inputs.version }}
      EVENT_VALUE: ${{ github.event.client_payload.version_tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Set variable
        id: set-var
        run: |
          [ -z ${MANUAL_VALUE} ] && echo "not defined" || export IMAGE_TAG=${MANUAL_VALUE}
          [ -z ${EVENT_VALUE} ] && echo "not defined" || export IMAGE_TAG=${EVENT_VALUE}

      - name: Check variable
        run: |
          printenv
