name: Repository Dispatch

on:
  repository_dispatch:
    types: [DEV Deploy Service]
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "release version (x.x.x)"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set variable
        id: set-var
        outputs: image_tag
        with:
          MANUAL_VALUE: ${{ github.event.inputs.version }}
          EVENT_VALUE: ${{ github.event.client_payload.version_tag }}
        run: |
          [ -z ${MANUAL_VALUE} ] && echo "not defined" || export image_tag=${MANUAL_VALUE}
          [ -z ${EVENT_VALUE} ] && echo "not defined" || export image_tag=${EVENT_VALUE}

      - name: Check variable
        needs: set-var
        run: |
          printenv
          echo ${{ steps.set-var.outputs.image_tag }}
